name: CI-Client

on:
  push:
    paths:
      - 'todo-app-client/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-app-client

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.17.0'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn run lint
