name: Deploy Client to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_run:
    workflows: ["CI-Client"]
    types:
      - completed
    branches:
      - master

jobs:
  build-and-deploy:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-app-client

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
